version: '3.4'
services:
  mongodb_server:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    container_name: $MONGO_HOSTNAME
    ports:
      - $MONGO_PORT:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOTUSER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - mongodb_server_data:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:   
      - $MONGO_EXPRESS_PORT:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_ROOTUSER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGO_ROOTUSER:$MONGO_ROOT_PASSWORD@$MONGO_HOSTNAME:$MONGO_PORT/
    depends_on: 
      - mongodb_server

  backend:
    build: .
    volumes:
      - /home/node/app/node_modules/
      - .:/home/node/app
    ports:
      - $APP_PORT:3000
    depends_on: 
      - mongodb_server
    env_file: .env
    environment: 
      - MONGO_HOSTNAME=$MONGO_HOSTNAME

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontendDev
    volumes:
      - /home/node/app/node_modules/
      - ./frontend:/home/node/app
    ports:
      - $VUE_PORT:8080
    env_file: .env
    depends_on: 
      - backend

volumes: 
  mongodb_server_data: